name: "Semgrep Scan"

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  # schedule:
  #   - cron: '41 8 * * 3'
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep
        run: |
          curl -L https://github.com/returntocorp/semgrep/releases/download/v0.76.0/semgrep-ci -o semgrep-ci
          chmod +x semgrep-ci
          ls -lrt
          ./semgrep-ci --config=auto .
